server:
  port: 8081
## configurações do datasource do spring
spring:
 # REST   
  data:
    rest:
      base-path: rest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate: 
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      showSql: true
      hbm2ddl: true
      ddlAuto: update
      
  # JACKSON
  jackson:
    serialization:
      INDENT_OUTPUT: true